### PR TITLE
replace call to filter function with better regex

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
What do you think @Fuzzyma? I think it's cleaner than f1d9f615

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Jetzt. Its a better regex but the problem with leading or trailing spaces remains.
Try:

```
console.log('a b c  '.split('/s+')
```

You should see it then

**Comment by dotnetCarpenter** [comment]
Well, for that we could easily do `console.log(' a b c  '.trim().split('/s+'))`. But then the question is if we prefer
```js
// parse points
array = array.trim().split(/\s+|,/)
```
over
```js
// parse points
array = array.split(/\s|,/).filter(function(a){ return a !== '' })
```

**Comment by Fuzzyma** [comment]
trim is a good solution. Go with yours + trim

**Comment by dotnetCarpenter** [comment]
Hmm... something weird is going on with my commits and github. The current commit on travis is not my latest commit...

**Comment by dotnetCarpenter** [comment]
ahh, it was a conflict. Fixed

**Pull request merged**
