### PR TITLE
Backports the fix to #409 from the master branch to v1.x branch.

### PR DESCRIPTION
**Pull request by pjfsilva**
Backports commit cf783fca1213d26b50bc07af0ca7e2b0f6385401
Backports the fix for #409 "SvgPathSeg is removed in Chrome 48".
This change fixes 53 test failures on Chrome 48+ (error: 'TypeError: Cannot read property 'numberOfItems' of undefined'.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
did you run the tests in chrome? Also I am pretty sure you missed 2 commits which fixes issues with this fix (dd7cc2f5104d488b0ba85366e14fae57edb767b7 and dd2ad7824d546242468992436d9a631a60294e28)

**Comment by pjfsilva** [comment]
Yes, ran tests on Chrome 48 and 51 canary. All 53 tests that were failing because of SvgPathSeg being removed on Chrome 48 (error: 'TypeError: Cannot read property 'numberOfItems' of undefined'.) now run correctly.

I wasn't aware of any further commits related to this, since all tests are now working. I'm not sure if those are easy to backport to v1.x, do you want me to try to backport also those or we do different PRs?

**Comment by pjfsilva** [comment]
Updated PR to include dd7cc2f and dd2ad78.
patharray.js is now synchronized to HEAD on master branch

**Comment by Fuzzyma** [comment]
I wasnt speaking from the tests *before* the fix but *after*. Are all tests ok after applying this patch?
If so I will merge it immediately

**Comment by pjfsilva** [comment]
OK, got it.

There is 1 test failing both *before* and *after* on Chrome 48 and 51 (and IE and FF) but it doesn't seem to be related to this PR. I believe that test is not correct but I don't have enough background to understand if the spec is wrong or there is a real problem.

Test failing:
`Regex testers isEvent is false without a namespace`

That test doesn't exist anymore on master and neither the isEvent regex. Other than this one, all tests are OK.

**Comment by Fuzzyma** [comment]
Published under 1.1.1

**Pull request merged**
