### PR TITLE
added svg.js.d.ts

### PR DESCRIPTION
**Pull request by rdfriedl**
seeing as typescript is starting to get more popular.
and with angular2 in beta, i thought it would be a good time to write the typescript definitions for this library.
i dont own all the credit for the definitions, i started with the definitions i found on http://definitelytyped.org/ and expanded on that. [here is the original](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/svgjs/svgjs.d.ts)

anyways feel free to review / change it since im sure i miss a few things :D

also i did not write the definitions for SVG.FX and the animations in general, i ran out of time :D

### CODE REVIEW

**Comment by rdfriedl** [comment]
i also just finished one for svg.filter.js so if you want i can create a PR for that one to.

the reason i made this one and the one for svg.filter.js is because im currently working on a typescript project and i need to use svg.js (because its very useful) :D

**Comment by Fuzzyma** [comment]
I guess thats a stupid question but I dont know typescript: so what is that for?

**Comment by rdfriedl** [comment]
in simplest form they are files that explain to typescript what each function / property in the library dose.
that way it can know now to handle type checking for when the user try to use the library

so for example if it write:
```typescript
var canvas:SVG.Doc = new SVG('#some-svg');
```
_the `:SVG.Doc` tells typescripts that my var is going to contain a SVG.Doc class_

but by default typescript dose not know how to handle other libraries.
so you write the definition files to tell is that `SVG()` is a functions and that `SVG.Doc` is a class that has certain properties and methods.

if you want to read more about it the documentation is  [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Writing%20Declaration%20Files.md)

**Comment by Fuzzyma** [comment]
Thanks for you work! I think we can merge this!

**Comment by Linkviii** [comment]
This doesn't seem to be published anywhere? Typings has an old (the original source?) definition from DefinitelyTyped.

**Comment by Fuzzyma** [comment]
Sorry, I dont get your point. As far as I can tell the typings got corrected before beeing merged here

**Comment by Linkviii** [comment]
```
$typings search svgjs
Viewing 2 of 2

NAME            SOURCE HOMEPAGE              DESCRIPTION VERSIONS UPDATED
svgjs           dt     http://www.svgjs.com/             1        2016-03-17T12:06:54.000Z
svgjs.draggable dt     http://www.svgjs.com/             1        2016-06-02T14:39:50.000Z
```
installed dt~svgjs and the definition does not match the one in this repository.

**Comment by Fuzzyma** [comment]
I dont even know that you have to publish this typescript definitions as extra again. I am pretty sure http://definitelytyped.org/ published that.

**Comment by Linkviii** [comment]
Searching for svgjs with Typings only yields the DefinitelyTyped definition is what I'm saying.

**Comment by rdfriedl** [comment]
i dont think this version is on Typings (DefinitelyTyped)
i never put it up there because im not familiar with how DefinitelyTyped works, though feel free to put it up :D

**Pull request merged**
