### PR TITLE
Unittest

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
I wanted to work on #525 by writing a failing test but to my surprise I couldn't run `npm test` and when I finally ran the jasmine test on my local server, I saw tests failing.

So instead of working on #525, I've updated the test suite so it can run on travis. I think that makes it more clear to everyone, when tests are failing. I also updated the dependencies and made sure that they work out-of-the-box (like gulp).

If you want it to run on travis, @wout, have to enable it. And you will want to update the badge in the README.md.

There is still some difference between running the tests via Karma and just opening the test suite in a browser. Not sure why yet, but I will try to iron it out in later commits.

But I hope the authors of the tests will take a look and see if any of their tests are failing.

The manual browser test has 5 failing tests (7 if tests are run random):
1.Element point() creates a point from screen coordinates transformed in the elements space `Expected -22 to be close to -21.`
2. Matrix inverse() inverses matrix `Expected 'matrix(0.5,0,0,0.20000000298023224,-2,-0.6000000238418579)' to be 'matrix(0.5,0,0,0.2,-2,-0.6)'.`
3. Text y() returns the value of y without an argument `Expected -4.470348358154297e-8 to be 0.`
4. PathArray size() resizes all points in a arc path `Expected 'M80 80A600 200 0 0 0 680 280L680 80Z ' to be 'M80 80A599.9998982747568 199.9999660915856 0 0 0 679.9998982747568 279.99996609158563L679.9998982747568 80Z '.`
5. FX at() sets the progress to the specified position `Expected 1475598310479 to be less than 1475598310479, 0.0001.`

Whereas the cli version has 13 failing tests:
1. PathArray size() resizes all points in a arc path FAILED
	Expected 'M80 80A600 200 0 0 0 680 280L680 80Z ' to be 'M80 80A599.9998982747568 199.9999660915856 0 0 0 679.9998982747568 279.99996609158563L679.9998982747568 80Z '.
	@spec/spec/array.js:77:7
2. Element svg() without an argument returns full raw svg when called on the main svg doc FAILED
	Expected '<svg id="SvgjsSvg1335" width="100" height="100" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>' to be '<svg id="SvgjsSvg1001" width="100" height="100" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>'.
	@spec/spec/element.js:586:9
3. Element point() creates a point from screen coordinates transformed in the elements space FAILED
	Expected -22 to be close to -21.
	@spec/spec/element.js:653:7
4. Matrix inverse() inverses matrix FAILED
	Expected 'matrix(0.5,0,0,0.20000000298023224,-2,-0.6000000238418579)' to be 'matrix(0.5,0,0,0.2,-2,-0.6)'.
	@spec/spec/matrix.js:173:7
5. Point initialization without a source encountered a declaration exception FAILED
	TypeError: point is not a function in spec/spec/point.js (line 8)
	@spec/spec/point.js:8:7
6. Point morph() stores a given point for morphing FAILED
	Expected ({ x: undefined, y: undefined }) to equal matrix(1,0,0,1,0,0).
	@spec/spec/point.js:83:7
7. Point at() returns a morphed point at a given position FAILED
	ReferenceError: matrix1 is not defined in spec/spec/point.js (line 99)
	@spec/spec/point.js:99:11
8. Point transform() returns a point transformed with given matrix FAILED
	ReferenceError: matrox is not defined in spec/spec/point.js (line 110)
	@spec/spec/point.js:110:7
9. Sugar fill() returns the value with no argument given FAILED
	Expected SvgjsRect2145 to be 'red'.
	@spec/spec/sugar.js:21:7
10. Sugar () returns the value with no argument given FAILED
	Expected SvgjsRect2147 to be 'red'.
	@spec/spec/sugar.js:47:7
11. Sugar svg() without an argument returns full raw svg when called on the main svg doc FAILED
	Expected '<svg id="SvgjsSvg1335" width="100" height="100" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>' to be '<svg id="SvgjsSvg1000" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="100" height="100"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>'.
	@spec/spec/sugar.js:609:9
12. Sugar point() creates a point from screen coordinates transformed in the elements space FAILED
	Expected -22 to be close to -3.
	@spec/spec/sugar.js:676:7
13. Text y() returns the value of y without an argument FAILED
	Expected -4.470348358154297e-8 to be 0.
	@spec/spec/text.js:34:7

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Woow - huge PR. Nice work.
I should note, that we used chrome to run the jasmine test suite. As you can see many of the failing tests are rounding errors. Different browsers delivered different results. Thats why we took chrome as base. Additionally the string representation of a tag after adding attributes to it differs in browsers. Attributes appear in different order. Same solution here.
For all these other failing tests we have to take a deeper look.
I have not one failing test in my chrome browser.

**Comment by dotnetCarpenter** [comment]
@Fuzzyma Well, I still get 1 failing test in Chromium 52.0:
```
FX at() sets the progress to the specified position
Expected 1475668226701 to be less than 1475668226701, 0.0001.
```

And I get 10 failing tests when I run the test suite via Karma. But all of them seem to be load script issue except 1:
```
Chromium 52.0.2743 (Ubuntu 0.0.0) Element svg() without an argument returns full raw svg when called on the main svg doc FAILED
	Expected '<svg id="SvgjsSvg1335" width="100" height="100" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>' to be '<svg id="SvgjsSvg1001" width="100" height="100" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs"><rect width="100" height="100"></rect><circle r="50" cx="50" cy="50" fill="#ff0066"></circle></svg>'.
	    at Object.<anonymous> (spec/spec/element.js:586:28)
```

As a *Collaborator* you should be able to turn on travis for svg.js. Go ahead and [turn in on now](https://travis-ci.com/), so we can get the results in this PR.

**Comment by Fuzzyma** [comment]
That one is related to https://github.com/wout/svg.js/pull/504 I guess.
The error you get from the browsers is again ordering of attributes in the svg output (which works fine in chrome 53).
I will do that as soon as I spoke with wout about that!

**Comment by dotnetCarpenter** [comment]
I changed browser to Chromium on Travis, since it is preinstalled. Version 37.0.2062 is the newest version in the Travis Ubuntu Precise apt source. I know it's old but I see the same test fail on 52.0.
Locally the test suite will run in Chrome and crash if you don't have Chrome installed.

I think I will make it so it changes to Chromium locally if you don't have Chrome installed. But this will only work on linux because I don't have time to test on Windows.

Personally, I think it's unfortunate that you choose Chrome and not Firefox as test base.

I will go to Greenland tomorrow and have no idea about the quality of Internet access I can expect. So this might be goodbye for now. I'll be back in a month.

**Comment by Fuzzyma** [comment]
We could move to FF if this makes work much easier. However someone would need to rewrite the tests (or make them more lax so they work in all browsers).
Have a good time in Greenland and thx for your contribution!

**Comment by dotnetCarpenter** [comment]
The reasons why I think Firefox is a better base is:
1. Chrome is more ambiguous, you have Chrome and Chromium
2. Firefox is the standard browser in most linux distributions
3. **Firefox's SVG implementation seems more buggy than the webkit/blink
counter part**
4. Firefox is not backed my evil corp - see mr. robot ::-):

Since I have had more trouble with SVG in Firefox, I think developing
against that browser will make `svg.js` more resilient.
So Firefox is a bit less work when it comes to creating a cross platform
testing tool, but in general I don't think switching to Firefox will make
development easier. Only `svg.js` will become a better product.

**Comment by Fuzzyma** [comment]
I though I responsed already but looks like I forgot that.
I guess your points are valid. We will rewrite the tests so they will match firefox' behavior.
What is needed from my side (beside the test rewriting) to make this work? I guess just merge this PR and flip the switch on the travis side?

**Comment by dotnetCarpenter** [comment]
Hi @Fuzzyma. I'm in Greenland on a metered connection. If you ever get the
chance to visit, you definitely should - it's the most beautiful country I
have ever visited.

About what is needed, yes - you just need to merge and flip the switch. But
I would like to spend some hours today going through everything. I can
probably make some of the failed tests pass before you merge.

Just to be sure, we are switching to Firefox, so I can remove the
Chrome/Chromium stuff?
So one point I need to do, is to switch back to Firefox before you merge.

**Comment by Fuzzyma** [comment]
Yes we will switch to firefox. Wout and me both agree with your arguments.
I realized that only repository admins can flip the switch so wout has to do it. But thats no problem.

Have fun in Greenland! I can only imagine how it is there. Definitely on my list now :D

**Comment by dotnetCarpenter** [comment]
My availability is a bit flaky at the moment. I just got Internet access again. I think this PR is ready to be merged but there is two issues that would be nice to close before merging. I need help with both.

1. It would be nice if we could get the unit tests to pass before merging. Both @wout and @Fuzzyma has push rights to this branch/repo. So you can fix code to your heart's content.

2. Right now travis is using Firefox 38.0 to run the tests which is very old. I'm able to [install Firefox beta (50.0)](https://travis-ci.org/dotnetCarpenter/svg.js/builds/166104969#L330) but I'm not able to get travis/karma to use the new version of Firefox to run the tests. I've asked at SO but haven't got any answers: http://stackoverflow.com/questions/39937099/newest-firefox-on-travis-ci-is-not-used-by-karma

Lastly - travis need to be turn on for this repo by @wout and PR's should pass on travis as a predicate before merging. The latter is in github setup for `svg.js`.

**Comment by Fuzzyma** [comment]
I updated all tests so they pass in Firefox and Chrome.
Please do not touch the version numbers in a PR. This is done in the final release commit to avoid any confusion.
Thanks for your effort!

**Comment by dotnetCarpenter** [comment]
@Fuzzyma thanks. I edited the version number by mistake - sorry. I didn't see that you updated this PR. I'll back out my changes to `spec/spec/array.js`

**Comment by dotnetCarpenter** [comment]
@Fuzzyma I think this PR is ready to be merged.

**Comment by wout** [comment]
@dotnetCarpenter Thank you so much for all your work on this! And @Fuzzyma, of course you too :)

**Comment by Fuzzyma** [comment]
@dotnetCarpenter can we let travis build the library from source before testing in case someone only commited to the src folder? Maybe as additional test which is not critical but informative?!?

**Comment by dotnetCarpenter** [comment]
sure - 4d9f4f9
<https://github.com/wout/svg.js/commit/4d9f4f9583e102118e08f6a1c777896901648799>
Now, travis will build via gulp before running the test suite.

**Pull request merged**
