### PR TITLE
Transform lists in IE11

### PR DESCRIPTION
**Pull request by rayglover**
IE11 doesn't use a comma to delimit transform-list elements. This PR intends to make parsing matrix transforms more in-line with the W3C spec.

### CODE REVIEW

**Comment by eXxi** [comment]
Thank you very much :) Moving a group in IE11 is not possible without this fix.

**Comment by Fuzzyma** [comment]
If you could run the gulp one time and add this to your PR i will accept it

**Comment by rayglover** [comment]
Merged and rebuilt (still v2.0.5)

**Comment by bubenshchykov** [comment]
@rayglover thanks man you rock!
@Fuzzyma looking forward to have it on bower :)

**Pull request merged**
